### ISSUE TITLE
error of 'make'

### ISSUE THREAD

**Issue by ghost** [kysucix/fusibile#13]
Hello, I got the problem when I run 'make', the errors are as follows, could you please help me?

[ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
In file included from /test/fusibile-master/globalstate.h:21:0,
                 from /test/fusibile-master/fusibile.cu:9:
/usr/local/cuda/include/cuda_gl_interop.h:66:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
CMake Error at fusibile_generated_fusibile.cu.o.cmake:219 (message):
  Error generating
  /test/fusibile-master/CMakeFiles/fusibile.dir//./fusibile_generated_fusibile.cu.o

CMakeFiles/fusibile.dir/build.make:63: recipe for target 'CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o' failed
make[2]: *** [CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fusibile.dir/all' failed
make[1]: *** [CMakeFiles/fusibile.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ghost** [comment]
I have solved the problem. Thanks.

**Comment by luhairong11** [comment]
I have solved the problem, too.

**Comment by anilesec** [comment]
@luhairong11  How did you solve this problem? I am having the same issue. Any hints would be useful?

**Comment by AddASecond** [comment]
> I have solved the problem. Thanks.

@ghost  Hi could you please share about how did you solve this?

I meet this problem too. install opengl does not work

**Comment by zzy0731** [comment]
hi ,can you share how do you solved the questiion ,  I have meet a same question too

**Comment by bobfacer** [comment]
> 
install opengl may work in a RTX 2080Ti machine

**Comment by bobfacer** [comment]
follow the link to install ioengl on ubuntu18.04 RTX 2080Ti.
[https://www.wikihow.com/Install-Mesa-(OpenGL)-on-Linux-Mint](url)
