### ISSUE TITLE
How to change the point cloud results to RGB?

### ISSUE THREAD

**Issue by ewrfcas** [kysucix/fusibile#18]
I can only get grayscale point clouds.
![image](https://user-images.githubusercontent.com/12042259/168477535-e77bcc76-7978-4a65-9e88-7fe51861f277.png)

**Comment by ewrfcas** [comment]
Solved.
Using this project can get RGB results.
https://github.com/YoYo000/fusibile

**Comment by AsDeadAsADodo** [comment]
hello! I'm wondering if you encounter segment fault (core dumped) issue while runing fusibile?
