### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by pogilon** [kysucix/fusibile#6]
Hello, I am trying to compile the algorithm and when doing make I get the following error. Any idea or help would be greatly appreciated. Thanks!

"make
[ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_30'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 49 registers, 332 bytes cmem[0], 20 bytes cmem[2]
ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_52'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 56 registers, 332 bytes cmem[0], 20 bytes cmem[2]
Scanning dependencies of target fusibile
[ 66%] Building CXX object CMakeFiles/fusibile.dir/main.cpp.o
In file included from /media/smarty/Storage2/tools/fusibile/main.cpp:32:0:
/media/smarty/Storage2/tools/fusibile/helper_cuda.h: In function ‘const char* _cudaGetErrorEnum(cudaError_t)’:
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:38:12: warning: enumeration value ‘cudaErrorNvlinkUncorrectable’ not handled in switch [-Wswitch]
     switch (error)
            ^
/media/smarty/Storage2/tools/fusibile/helper_cuda.h: In function ‘const char* _cudaGetErrorEnum(CUresult)’:
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_PEER_ACCESS_UNSUPPORTED’ not handled in switch [-Wswitch]
     switch (error)
            ^
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_PTX’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_GRAPHICS_CONTEXT’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_NVLINK_UNCORRECTABLE’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_ILLEGAL_ADDRESS’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_HARDWARE_STACK_ERROR’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_ILLEGAL_INSTRUCTION’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_MISALIGNED_ADDRESS’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_ADDRESS_SPACE’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_PC’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_NOT_PERMITTED’ not handled in switch [-Wswitch]
/media/smarty/Storage2/tools/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_NOT_SUPPORTED’ not handled in switch [-Wswitch]
"

**Comment by philleer** [comment]
I have encounted some similar problem when i run **'make'** command
```
[ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_30'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 47 registers, 332 bytes cmem[0], 20 bytes cmem[2]
ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_52'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at fusibile_generated_fusibile.cu.o.cmake:266 (message):
  Error generating file
  /home/cvlab/mvsnet/fusibile/build/CMakeFiles/fusibile.dir//./fusibile_generated_fusibile.cu.o

CMakeFiles/fusibile.dir/build.make:63: recipe for target 'CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o' failed
make[2]: *** [CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fusibile.dir/all' failed
make[1]: *** [CMakeFiles/fusibile.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
What should i do now?
Any one can help? Much thx!

**Comment by boni-hu** [comment]
I have encounted  the same problem as you, when i  run 'make' command. What should i do now?

Sincerely,
Hu Boni

**Comment by philleer** [comment]
> I have encounted some similar problem when i run **'make'** command
> 
> ```
> [ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
> ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
> ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_30'
> ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
>     8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 47 registers, 332 bytes cmem[0], 20 bytes cmem[2]
> ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
> ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_52'
> ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
>     8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
> /usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
> /usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
>    return (char *) memcpy (__dest, __src, __n) + __n;
>                                           ^
> CMake Error at fusibile_generated_fusibile.cu.o.cmake:266 (message):
>   Error generating file
>   /home/cvlab/mvsnet/fusibile/build/CMakeFiles/fusibile.dir//./fusibile_generated_fusibile.cu.o
> 
> CMakeFiles/fusibile.dir/build.make:63: recipe for target 'CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o' failed
> make[2]: *** [CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fusibile.dir/all' failed
> make[1]: *** [CMakeFiles/fusibile.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> What should i do now?
> Any one can help? Much thx!
-----------------------------------------------------------------------------------
Finally, having tried several googled solutions, i solved my problem.

Maybe it is because of the version of g++, i think.

Some guys come across similar issue when they compile opencv, cmake is all well and make throws error:
```
error:1 /usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope 
```
then he add the following command in the **CMakeLists.txt** to make the system compatible with g++5.4.0
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
```
So i do the same thing in my **CMakeLists.txt** for ```fusibile```
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
```
and now it is ok for me!
```
[ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_30'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 47 registers, 332 bytes cmem[0], 20 bytes cmem[2]
ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_52'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
Scanning dependencies of target fusibile
[ 66%] Building CXX object CMakeFiles/fusibile.dir/main.cpp.o
In file included from /home/cvlab/mvsnet/fusibile/main.cpp:32:0:
/home/cvlab/mvsnet/fusibile/helper_cuda.h: In function ‘const char* _cudaGetErrorEnum(CUresult)’:
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_PEER_ACCESS_UNSUPPORTED’ not handled in switch [-Wswitch]
     switch (error)
            ^
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_PTX’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_GRAPHICS_CONTEXT’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_ILLEGAL_ADDRESS’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_HARDWARE_STACK_ERROR’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_ILLEGAL_INSTRUCTION’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_MISALIGNED_ADDRESS’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_ADDRESS_SPACE’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_PC’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_NOT_PERMITTED’ not handled in switch [-Wswitch]
/home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_NOT_SUPPORTED’ not handled in switch [-Wswitch]
[100%] Linking CXX executable fusibile
[100%] Built target fusibile
```
BTW, here is my computer configuration
```
Distributor ID: Ubuntu

Description: Ubuntu 16.04.6 LTS

Release: 16.04

Codename: xenial

Processor: Intel CoreTM i5-6500 CPU @3.20GHz x 4

Graphics: GeForce GTX 1080/PCIe/SSE2

OS type: 64-bit

G++: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by kikiwindsky** [comment]
I also have this problem and it seems that OpenGl is not install 
After adding the command : 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")`
in the CMakeLists.txt
I install the library via:
```
sudo apt-get install mesa-common-dev
sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev
```
and it is OK for me 

```
root@905827a30713:/MVSNet/fusibile# make          
[ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
/MVSNet/fusibile/fusibile.cu(178): warning: variable "used_list" was set but never used

ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_60'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
/MVSNet/fusibile/fusibile.cu(178): warning: variable "used_list" was set but never used

/MVSNet/fusibile/fusibile.cu: In function 'void copy_point_cloud_to_host(GlobalState&, int, PointCloudList&)':
/MVSNet/fusibile/fusibile.cu:311:60: warning: 'texture4[3]' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 pc_list.points[count].texture4[3] = texture4[3];
                                                            ^
/MVSNet/fusibile/fusibile.cu:310:60: warning: 'texture4[2]' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 pc_list.points[count].texture4[2] = texture4[2];
                                                            ^
/MVSNet/fusibile/fusibile.cu:309:60: warning: 'texture4[1]' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 pc_list.points[count].texture4[1] = texture4[1];
                                                            ^
/MVSNet/fusibile/fusibile.cu:308:60: warning: 'texture4[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 pc_list.points[count].texture4[0] = texture4[0];
                                                            ^
Scanning dependencies of target fusibile
[ 66%] Building CXX object CMakeFiles/fusibile.dir/main.cpp.o
In file included from /MVSNet/fusibile/main.cpp:32:0:
/MVSNet/fusibile/helper_cuda.h: In function 'const char* _cudaGetErrorEnum(cudaError_t)':
/MVSNet/fusibile/helper_cuda.h:38:12: warning: enumeration value 'cudaErrorNvlinkUncorrectable' not handled in switch [-Wswitch]
     switch (error)
            ^
/MVSNet/fusibile/helper_cuda.h:38:12: warning: enumeration value 'cudaErrorJitCompilerNotFound' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:38:12: warning: enumeration value 'cudaErrorCooperativeLaunchTooLarge' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h: In function 'const char* _cudaGetErrorEnum(CUresult)':
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_PEER_ACCESS_UNSUPPORTED' not handled in switch [-Wswitch]
     switch (error)
            ^
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_INVALID_PTX' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_INVALID_GRAPHICS_CONTEXT' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_NVLINK_UNCORRECTABLE' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_JIT_COMPILER_NOT_FOUND' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_ILLEGAL_ADDRESS' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_HARDWARE_STACK_ERROR' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_ILLEGAL_INSTRUCTION' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_MISALIGNED_ADDRESS' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_INVALID_ADDRESS_SPACE' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_INVALID_PC' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_NOT_PERMITTED' not handled in switch [-Wswitch]
/MVSNet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_NOT_SUPPORTED' not handled in switch [-Wswitch]
[100%] Linking CXX executable fusibile
[100%] Built target fusibile
```

**Comment by zenithfang** [comment]
I add this in the first line of CMakeList.txt. But it still cannot work. My g++ version is g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516. Could you give me some advise?

> > I have encounted some similar problem when i run **'make'** command
> > ```
> > [ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
> > ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
> > ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_30'
> > ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
> >     8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> > ptxas info    : Used 47 registers, 332 bytes cmem[0], 20 bytes cmem[2]
> > ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
> > ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_52'
> > ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
> >     8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> > ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
> > /usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
> > /usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
> >    return (char *) memcpy (__dest, __src, __n) + __n;
> >                                           ^
> > CMake Error at fusibile_generated_fusibile.cu.o.cmake:266 (message):
> >   Error generating file
> >   /home/cvlab/mvsnet/fusibile/build/CMakeFiles/fusibile.dir//./fusibile_generated_fusibile.cu.o
> > 
> > CMakeFiles/fusibile.dir/build.make:63: recipe for target 'CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o' failed
> > make[2]: *** [CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o] Error 1
> > CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fusibile.dir/all' failed
> > make[1]: *** [CMakeFiles/fusibile.dir/all] Error 2
> > Makefile:83: recipe for target 'all' failed
> > make: *** [all] Error 2
> > ```
> > 
> > 
> > What should i do now?
> > Any one can help? Much thx!
> 
> Finally, having tried several googled solutions, i solved my problem.
> 
> Maybe it is because of the version of g++, i think.
> 
> Some guys come across similar issue when they compile opencv, cmake is all well and make throws error:
> 
> ```
> error:1 /usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope 
> ```
> 
> then he add the following command in the **CMakeLists.txt** to make the system compatible with g++5.4.0
> 
> ```
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
> ```
> 
> So i do the same thing in my **CMakeLists.txt** for `fusibile`
> 
> ```
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
> ```
> 
> and now it is ok for me!
> 
> ```
> [ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
> ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
> ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_30'
> ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
>     8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 47 registers, 332 bytes cmem[0], 20 bytes cmem[2]
> ptxas info    : 77824 bytes gmem, 72 bytes cmem[3]
> ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_52'
> ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
>     8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
> Scanning dependencies of target fusibile
> [ 66%] Building CXX object CMakeFiles/fusibile.dir/main.cpp.o
> In file included from /home/cvlab/mvsnet/fusibile/main.cpp:32:0:
> /home/cvlab/mvsnet/fusibile/helper_cuda.h: In function ‘const char* _cudaGetErrorEnum(CUresult)’:
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_PEER_ACCESS_UNSUPPORTED’ not handled in switch [-Wswitch]
>      switch (error)
>             ^
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_PTX’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_GRAPHICS_CONTEXT’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_ILLEGAL_ADDRESS’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_HARDWARE_STACK_ERROR’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_ILLEGAL_INSTRUCTION’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_MISALIGNED_ADDRESS’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_ADDRESS_SPACE’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_INVALID_PC’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value 'CUDA_ERROR_NOT_PERMITTED’ not handled in switch [-Wswitch]
> /home/cvlab/mvsnet/fusibile/helper_cuda.h:293:12: warning: enumeration value ‘CUDA_ERROR_NOT_SUPPORTED’ not handled in switch [-Wswitch]
> [100%] Linking CXX executable fusibile
> [100%] Built target fusibile
> ```
> 
> BTW, here is my computer configuration
> 
> ```
> Distributor ID: Ubuntu
> 
> Description: Ubuntu 16.04.6 LTS
> 
> Release: 16.04
> 
> Codename: xenial
> 
> Processor: Intel CoreTM i5-6500 CPU @3.20GHz x 4
> 
> Graphics: GeForce GTX 1080/PCIe/SSE2
> 
> OS type: 64-bit
> 
> G++: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> ```
